VERSION = (0, 1, 1)

GEO_LEVEL_COUNTRY = 0
GEO_LEVEL_REGION = 1
GEO_LEVEL_CITY = 2

LISTINGS_GEO_LEVELS = (
    (GEO_LEVEL_COUNTRY, 'Country'),
    (GEO_LEVEL_REGION, 'Region'),
    (GEO_LEVEL_CITY, 'City')
)
